spring:
  application:
    name: my-app
  zipkin:
    baseUrl: http://localhost:9411/
    discoveryClientEnabled : false
    sender:
      type:  web
    service:
      name: my-app
  sleuth:
    sampler:
      probability: 1.0
    web:
      skipPattern: (^cleanup.*)
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
logging:
  level:
    org:
      springframework:
        web: debug