spring:
  application:
    name: my-app
  zipkin:
    baseUrl: http://zipkin:9411/ #container ip or container name in docker compose
    discoveryClientEnabled : false
    sender:
      type:  web
    service:
      name: my-app
  sleuth:
    sampler:
      probability: 1.0
    web:
      skipPattern: (^cleanup.*)
server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka #container ip or container name in docker compose
  instance:
    preferIpAddress: true
logging:
  level:
    org:
      springframework:
        web: info
  file: logback.xml