spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    
 
  application:
    name: app-two
  zipkin:
    baseUrl: http://zipkin:9411/ #container ip or container name in docker compose
    discoveryClientEnabled : false
    sender:
      type:  web
    service:
      name: app-two
  sleuth:
    sampler:
      probability: 1.0
    web:
      skipPattern: (^cleanup.*)
server:
  port: 9001
#  servlet:
#    context-path: 
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka #container ip or container name in docker compose
    fetchRegistry: true
  instance:
    preferIpAddress: true
logging:
  level:
    org:
      springframework:
        web: info
  file: logback.xml
  
hibernate:
  datasource:
    jdbc-url: jdbc:mysql://db:3306/microservices?zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&useSSL=false
    user: root
    password: root
    driver-class: com.mysql.jdbc.Driver
    max-idle-time: 6
    min-pool-size: 3
    max-pool-size: 15
