spring:
  application:
    name: zuul
    
server:
  port: 8082
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka #container ip or container name in docker compose
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    
zuul:
  routes:
    myapp:
      path: /myapp/**
      serviceId: my-app
    apptwo:
      path: /apptwo/**
      serviceId: app-two
logging:
  level:
    org:
      springframework:
        web: info
  file: logback.xml